[package]
name = "bytes"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
duration-str = "0.17.0"
poise = "0.6.1"
r2d2 = "0.8.10"
r2d2_sqlite = "0.30.0"
rusqlite = "0.36.0"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
